name: observatory-dev
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3060:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./files/var/lib/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - loki
    networks:
      - container_network

  loki:
    image: grafana/loki:2.7.3
    ports:
      - "3100:3100"
    networks:
      - container_network

volumes:
  postgres_data:

networks:
  container_network:
    driver: bridge
