name: observatory-dev
services:
    postgres:
        image: postgres:latest
        restart: unless-stopped
        ports:
            - ${POSTGRES_PORT}:5432
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - postgres_data:/var/lib/postgresql/data

    grafana:
        image: grafana/grafana
        restart: unless-stopped
        ports:
            - '3060:3000'
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
        volumes:
            - ./grafana:/var/lib/grafana
        depends_on:
            - loki
        networks:
            - container_network

    loki:
        image: grafana/loki:2.7.3
        restart: unless-stopped
        ports:
            - '3100:3100'
        networks:
            - container_network

    redis:
        image: redis:latest
        restart: unless-stopped
        ports:
            - 6379:6379
        volumes:
            - redis:/data
        networks:
            - container_network

volumes:
    redis:
    postgres_data:

networks:
    container_network:
        driver: bridge
